---

name: Golang Backend CI

on:
  push:
    branches:
      - 'main'
      - 'release'
    paths:
      - 'src/**'
      - 'main.go'
      - 'Dockerfile'
      - '!k8s/**'

jobs: 
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.NEW_GITHUB_PAT }}
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: src
          file: Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:${{ env.SHORT_SHA }}
      - name: Update Kubernetes deployment file
        run: |
          sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/ecommerce-backend:${{ env.SHORT_SHA }}|g' golang-backend/deployment.yaml
      - name: Commit and push updated manifest
        run: |
          git config --local user.email "aleroawani18@gmail.com"
          git config --local user.name "Alero Awani"
          git add golang-backend/deployment.yaml
          git commit -m "Update image tag to ${{ env.SHORT_SHA }}" || exit 0
          git push
        